server:
  port: 9002

spring:
  application:
    name: product-service

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop?serverTimezone=UTC&useUnicode=true&charaterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  rabbitmq:
    host: 39.108.63.30
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://127.0.0.1:9411/ #server的请求地址
    sender:
      type: web   #数据的传输方式,已http形式向server端发送数据
  sleuth:
    sampler:
      probability: 1  #采样比 默认0.1 百分之10
#配置Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true  #使用ip地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #向服务中心注册服务id
    lease-renewal-interval-in-seconds: 5 #设置心跳间隔
    lease-expiration-duration-in-seconds: 10 #设置续约到期时间


#链路追踪日志
logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.cloud.sleuth: DEBUG
    
    
testConfig: product-Profile 111   
